// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Jison = require("jison");
var CalculatorJson = require("./calculator.json");

var calculator = new Jison.Parser(CalculatorJson);

console.log(calculator.generate());

exports.calculator = calculator;
/* calculator Not a pure module */
